/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products (active only unless includeInactive) */
        get: operations["getProducts"];
        put?: never;
        /** Create a product (admin) */
        post: operations["postProducts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a product by slug */
        get: operations["getProductsBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive a product (admin) */
        delete: operations["deleteProductsById"];
        options?: never;
        head?: never;
        /** Update a product (admin) */
        patch: operations["patchProductsById"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    getProducts: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: (string | null) | null;
                        priceCents: number;
                        currency: string;
                        stock: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
        };
    };
    postProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug: string;
                    name: string;
                    description?: (string | null) | null;
                    priceCents: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    slug: string;
                    name: string;
                    description?: (string | null) | null;
                    priceCents: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
                "multipart/form-data": {
                    slug: string;
                    name: string;
                    description?: (string | null) | null;
                    priceCents: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description Response for status 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: (string | null) | null;
                        priceCents: number;
                        currency: string;
                        stock: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getProductsBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: (string | null) | null;
                        priceCents: number;
                        currency: string;
                        stock: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    deleteProductsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: (string | null) | null;
                        priceCents: number;
                        currency: string;
                        stock: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    patchProductsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug?: string;
                    name?: string;
                    description?: (string | null) | null;
                    priceCents?: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    slug?: string;
                    name?: string;
                    description?: (string | null) | null;
                    priceCents?: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
                "multipart/form-data": {
                    slug?: string;
                    name?: string;
                    description?: (string | null) | null;
                    priceCents?: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: (string | null) | null;
                        priceCents: number;
                        currency: string;
                        stock: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
}
