/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products (active only; drafts included for admins) */
        get: operations["getProducts"];
        put?: never;
        /** Create a product (admin) */
        post: operations["postProducts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a product by slug */
        get: operations["getProductsBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive a product (admin) */
        delete: operations["deleteProductsById"];
        options?: never;
        head?: never;
        /** Update a product (admin) */
        patch: operations["patchProductsById"];
        trace?: never;
    };
    "/shipping/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get shipping options for a destination + subtotal */
        post: operations["postShippingQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shipping/validate-address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a shipping address and check we ship there */
        post: operations["postShippingValidate-address"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shipping/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List shipping zones with their rates (admin) */
        get: operations["getShippingZones"];
        put?: never;
        /** Create a shipping zone (admin) */
        post: operations["postShippingZones"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shipping/zones/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive a shipping zone (admin) */
        delete: operations["deleteShippingZonesById"];
        options?: never;
        head?: never;
        /** Update a shipping zone (admin) */
        patch: operations["patchShippingZonesById"];
        trace?: never;
    };
    "/shipping/zones/{zoneId}/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a rate to a zone (admin) */
        post: operations["postShippingZonesByZoneIdRates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shipping/rates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive a shipping rate (admin) */
        delete: operations["deleteShippingRatesById"];
        options?: never;
        head?: never;
        /** Update a shipping rate (admin) */
        patch: operations["patchShippingRatesById"];
        trace?: never;
    };
    "/checkout/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a Stripe Checkout session for a cart
         * @description Validates the cart against the catalogue, applies shipping, and returns a hosted Stripe Checkout URL. Prices are server-authoritative.
         */
        post: operations["postCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe webhook (checkout completion → order fulfillment) */
        post: operations["postCheckoutWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an order by id (for the checkout confirmation page) */
        get: operations["getCheckoutOrdersById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders (admin) */
        get: operations["getAdminOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an order with its items (admin) */
        get: operations["getAdminOrdersById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{id}/fulfillment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update fulfillment status / tracking (admin) */
        patch: operations["patchAdminOrdersByIdFulfillment"];
        trace?: never;
    };
    "/subscription-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active subscription plans */
        get: operations["getSubscription-plans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a subscription checkout for a plan */
        post: operations["postCheckoutSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email a Stripe Billing portal link */
        post: operations["postAccountPortal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subscription-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all subscription plans (admin) */
        get: operations["getAdminSubscription-plans"];
        put?: never;
        /** Create a subscription plan (admin) */
        post: operations["postAdminSubscription-plans"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subscription-plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate/deactivate a subscription plan (admin) */
        patch: operations["patchAdminSubscription-plansById"];
        trace?: never;
    };
    "/admin/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscriptions (admin) */
        get: operations["getAdminSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        email: (string | null) | null;
                        isAdmin: boolean;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getProducts: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: (string | null) | null;
                        priceCents: number;
                        currency: string;
                        stock: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
        };
    };
    postProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug: string;
                    name: string;
                    description?: (string | null) | null;
                    priceCents: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    slug: string;
                    name: string;
                    description?: (string | null) | null;
                    priceCents: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
                "multipart/form-data": {
                    slug: string;
                    name: string;
                    description?: (string | null) | null;
                    priceCents: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description Response for status 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: (string | null) | null;
                        priceCents: number;
                        currency: string;
                        stock: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getProductsBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: (string | null) | null;
                        priceCents: number;
                        currency: string;
                        stock: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    deleteProductsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: (string | null) | null;
                        priceCents: number;
                        currency: string;
                        stock: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    patchProductsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug?: string;
                    name?: string;
                    description?: (string | null) | null;
                    priceCents?: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    slug?: string;
                    name?: string;
                    description?: (string | null) | null;
                    priceCents?: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
                "multipart/form-data": {
                    slug?: string;
                    name?: string;
                    description?: (string | null) | null;
                    priceCents?: string | number;
                    currency?: string;
                    stock?: string | number;
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        slug: string;
                        name: string;
                        description: (string | null) | null;
                        priceCents: number;
                        currency: string;
                        stock: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    postShippingQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    country: string;
                    subtotalCents: string | number;
                };
                "application/x-www-form-urlencoded": {
                    country: string;
                    subtotalCents: string | number;
                };
                "multipart/form-data": {
                    country: string;
                    subtotalCents: string | number;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        zone: {
                            id: string;
                            name: string;
                        };
                        options: {
                            id: string;
                            name: string;
                            priceCents: number;
                            baseCents: number;
                            currency: string;
                            free: boolean;
                            minDeliveryDays: (number | null) | null;
                            maxDeliveryDays: (number | null) | null;
                        }[];
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "postShippingValidate-address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    line1: string;
                    line2?: (string | null) | null;
                    city: string;
                    postalCode: string;
                    country: string;
                    phone?: (string | null) | null;
                };
                "application/x-www-form-urlencoded": {
                    name: string;
                    line1: string;
                    line2?: (string | null) | null;
                    city: string;
                    postalCode: string;
                    country: string;
                    phone?: (string | null) | null;
                };
                "multipart/form-data": {
                    name: string;
                    line1: string;
                    line2?: (string | null) | null;
                    city: string;
                    postalCode: string;
                    country: string;
                    phone?: (string | null) | null;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        normalized: {
                            name: string;
                            line1: string;
                            line2?: (string | null) | null;
                            city: string;
                            postalCode: string;
                            country: string;
                            phone?: (string | null) | null;
                        };
                        shippable: boolean;
                        zone: ({
                            id: string;
                            name: string;
                        } | null) | null;
                    };
                };
            };
        };
    };
    getShippingZones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        countries: string[];
                        priority: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                        rates: {
                            id: string;
                            zoneId: string;
                            name: string;
                            priceCents: number;
                            currency: string;
                            freeAboveCents: (number | null) | null;
                            minDeliveryDays: (number | null) | null;
                            maxDeliveryDays: (number | null) | null;
                            active: boolean;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                    }[];
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    postShippingZones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    countries: string[];
                    priority?: string | number;
                    active?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    name: string;
                    countries: string[];
                    priority?: string | number;
                    active?: boolean;
                };
                "multipart/form-data": {
                    name: string;
                    countries: string[];
                    priority?: string | number;
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description Response for status 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        countries: string[];
                        priority: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    deleteShippingZonesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        countries: string[];
                        priority: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    patchShippingZonesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    countries?: string[];
                    priority?: string | number;
                    active?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    name?: string;
                    countries?: string[];
                    priority?: string | number;
                    active?: boolean;
                };
                "multipart/form-data": {
                    name?: string;
                    countries?: string[];
                    priority?: string | number;
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        countries: string[];
                        priority: number;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    postShippingZonesByZoneIdRates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    priceCents: string | number;
                    currency?: string;
                    freeAboveCents?: ((string | number) | null) | null;
                    minDeliveryDays?: ((string | number) | null) | null;
                    maxDeliveryDays?: ((string | number) | null) | null;
                    active?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    name: string;
                    priceCents: string | number;
                    currency?: string;
                    freeAboveCents?: ((string | number) | null) | null;
                    minDeliveryDays?: ((string | number) | null) | null;
                    maxDeliveryDays?: ((string | number) | null) | null;
                    active?: boolean;
                };
                "multipart/form-data": {
                    name: string;
                    priceCents: string | number;
                    currency?: string;
                    freeAboveCents?: ((string | number) | null) | null;
                    minDeliveryDays?: ((string | number) | null) | null;
                    maxDeliveryDays?: ((string | number) | null) | null;
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description Response for status 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        zoneId: string;
                        name: string;
                        priceCents: number;
                        currency: string;
                        freeAboveCents: (number | null) | null;
                        minDeliveryDays: (number | null) | null;
                        maxDeliveryDays: (number | null) | null;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    deleteShippingRatesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        zoneId: string;
                        name: string;
                        priceCents: number;
                        currency: string;
                        freeAboveCents: (number | null) | null;
                        minDeliveryDays: (number | null) | null;
                        maxDeliveryDays: (number | null) | null;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    patchShippingRatesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    priceCents?: string | number;
                    currency?: string;
                    freeAboveCents?: ((string | number) | null) | null;
                    minDeliveryDays?: ((string | number) | null) | null;
                    maxDeliveryDays?: ((string | number) | null) | null;
                    active?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    name?: string;
                    priceCents?: string | number;
                    currency?: string;
                    freeAboveCents?: ((string | number) | null) | null;
                    minDeliveryDays?: ((string | number) | null) | null;
                    maxDeliveryDays?: ((string | number) | null) | null;
                    active?: boolean;
                };
                "multipart/form-data": {
                    name?: string;
                    priceCents?: string | number;
                    currency?: string;
                    freeAboveCents?: ((string | number) | null) | null;
                    minDeliveryDays?: ((string | number) | null) | null;
                    maxDeliveryDays?: ((string | number) | null) | null;
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        zoneId: string;
                        name: string;
                        priceCents: number;
                        currency: string;
                        freeAboveCents: (number | null) | null;
                        minDeliveryDays: (number | null) | null;
                        maxDeliveryDays: (number | null) | null;
                        active: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    postCheckoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    items: {
                        slug: string;
                        quantity: string | number;
                    }[];
                    country: string;
                    shippingRateId: string;
                    email?: (string | null) | null;
                };
                "application/x-www-form-urlencoded": {
                    items: {
                        slug: string;
                        quantity: string | number;
                    }[];
                    country: string;
                    shippingRateId: string;
                    email?: (string | null) | null;
                };
                "multipart/form-data": {
                    items: {
                        slug: string;
                        quantity: string | number;
                    }[];
                    country: string;
                    shippingRateId: string;
                    email?: (string | null) | null;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url: string;
                        sessionId: string;
                        orderId: string;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 503 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    postCheckoutWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        received: boolean;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 503 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getCheckoutOrdersById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        status: string;
                        currency: string;
                        subtotalCents: number;
                        shippingCents: number;
                        taxCents: (number | null) | null;
                        totalCents: (number | null) | null;
                        email: (string | null) | null;
                        items: {
                            slug: string;
                            name: string;
                            unitPriceCents: number;
                            currency: string;
                            quantity: number;
                        }[];
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getAdminOrders: {
        parameters: {
            query?: {
                status?: "paid" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        status: string;
                        fulfillmentStatus: string;
                        email: (string | null) | null;
                        currency: string;
                        totalCents: (number | null) | null;
                        itemCount: number;
                        shipCountry: (string | null) | null;
                        shippingRateName: (string | null) | null;
                        trackingNumber: (string | null) | null;
                        /** Format: date-time */
                        createdAt: string;
                        paidAt: (string | null) | null;
                    }[];
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getAdminOrdersById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        status: string;
                        fulfillmentStatus: string;
                        email: (string | null) | null;
                        currency: string;
                        subtotalCents: number;
                        shippingCents: number;
                        taxCents: (number | null) | null;
                        totalCents: (number | null) | null;
                        shippingRateName: (string | null) | null;
                        trackingCarrier: (string | null) | null;
                        trackingNumber: (string | null) | null;
                        ship: {
                            name: (string | null) | null;
                            line1: (string | null) | null;
                            line2: (string | null) | null;
                            city: (string | null) | null;
                            postalCode: (string | null) | null;
                            country: (string | null) | null;
                        };
                        items: {
                            id: string;
                            slug: string;
                            name: string;
                            unitPriceCents: number;
                            currency: string;
                            quantity: number;
                        }[];
                        /** Format: date-time */
                        createdAt: string;
                        paidAt: (string | null) | null;
                        shippedAt: (string | null) | null;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    patchAdminOrdersByIdFulfillment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    fulfillmentStatus?: "new" | "packed" | "shipped";
                    trackingCarrier?: (string | null) | null;
                    trackingNumber?: (string | null) | null;
                };
                "application/x-www-form-urlencoded": {
                    /** @enum {string} */
                    fulfillmentStatus?: "new" | "packed" | "shipped";
                    trackingCarrier?: (string | null) | null;
                    trackingNumber?: (string | null) | null;
                };
                "multipart/form-data": {
                    /** @enum {string} */
                    fulfillmentStatus?: "new" | "packed" | "shipped";
                    trackingCarrier?: (string | null) | null;
                    trackingNumber?: (string | null) | null;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        status: string;
                        fulfillmentStatus: string;
                        email: (string | null) | null;
                        currency: string;
                        subtotalCents: number;
                        shippingCents: number;
                        taxCents: (number | null) | null;
                        totalCents: (number | null) | null;
                        shippingRateName: (string | null) | null;
                        trackingCarrier: (string | null) | null;
                        trackingNumber: (string | null) | null;
                        ship: {
                            name: (string | null) | null;
                            line1: (string | null) | null;
                            line2: (string | null) | null;
                            city: (string | null) | null;
                            postalCode: (string | null) | null;
                            country: (string | null) | null;
                        };
                        items: {
                            id: string;
                            slug: string;
                            name: string;
                            unitPriceCents: number;
                            currency: string;
                            quantity: number;
                        }[];
                        /** Format: date-time */
                        createdAt: string;
                        paidAt: (string | null) | null;
                        shippedAt: (string | null) | null;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "getSubscription-plans": {
        parameters: {
            query?: {
                productId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        productId: string;
                        name: string;
                        interval: string;
                        intervalCount: number;
                        priceCents: number;
                        currency: string;
                        active: boolean;
                    }[];
                };
            };
        };
    };
    postCheckoutSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    planId: string;
                    email?: (string | null) | null;
                };
                "application/x-www-form-urlencoded": {
                    planId: string;
                    email?: (string | null) | null;
                };
                "multipart/form-data": {
                    planId: string;
                    email?: (string | null) | null;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url: string;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 503 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    postAccountPortal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
                "application/x-www-form-urlencoded": {
                    /** Format: email */
                    email: string;
                };
                "multipart/form-data": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "getAdminSubscription-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        productId: string;
                        name: string;
                        interval: string;
                        intervalCount: number;
                        priceCents: number;
                        currency: string;
                        active: boolean;
                    }[];
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "postAdminSubscription-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    productId: string;
                    name: string;
                    /** @enum {string} */
                    interval: "week" | "month";
                    intervalCount?: string | number;
                    priceCents: string | number;
                };
                "application/x-www-form-urlencoded": {
                    productId: string;
                    name: string;
                    /** @enum {string} */
                    interval: "week" | "month";
                    intervalCount?: string | number;
                    priceCents: string | number;
                };
                "multipart/form-data": {
                    productId: string;
                    name: string;
                    /** @enum {string} */
                    interval: "week" | "month";
                    intervalCount?: string | number;
                    priceCents: string | number;
                };
            };
        };
        responses: {
            /** @description Response for status 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        productId: string;
                        name: string;
                        interval: string;
                        intervalCount: number;
                        priceCents: number;
                        currency: string;
                        active: boolean;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 503 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "patchAdminSubscription-plansById": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    active: boolean;
                };
                "application/x-www-form-urlencoded": {
                    active: boolean;
                };
                "multipart/form-data": {
                    active: boolean;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        productId: string;
                        name: string;
                        interval: string;
                        intervalCount: number;
                        priceCents: number;
                        currency: string;
                        active: boolean;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getAdminSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        planId: (string | null) | null;
                        productId: (string | null) | null;
                        email: (string | null) | null;
                        status: string;
                        currency: string;
                        amountCents: (number | null) | null;
                        currentPeriodEnd: (string | null) | null;
                        cancelAtPeriodEnd: boolean;
                        /** Format: date-time */
                        createdAt: string;
                    }[];
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
}
